# Generated by Django 3.2.6 on 2021-11-17 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogs', '0002_auto_20211117_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='Blog_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
